services:
  zai-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openai-api-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # 挂载 tokens.txt 文件（如果需要从文件读取 token）
      - ./tokens.txt:/app/data/tokens.txt:ro
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  api-network:
    driver: bridge

